### ISSUE TITLE
Confirming: is it dangerous to interrupt the script (e.g., via CTRL+C)?

### ISSUE THREAD

**Issue by xanoni** [prusnak/suez#28]
https://docs.lightning.engineering/lightning-network-tools/lnd/safety#prevent-data-corruption

> The following (non-exhaustive) list of things can lead to data corruption:
> [...]
> Aborting channel operation commands (see next chapter).
> [...]

Next chapter (https://docs.lightning.engineering/lightning-network-tools/lnd/safety#dont-interrupt-lncli-commands):

> Things can start to take a while to execute if a node has more than 50 to 100 channels. It is extremely important to never interrupt an lncli command if it is manipulating the channel database, which is true for the following commands:
> [...]
> updatechanpolicy
> [...]

Thus, I assume we should "never interrupt" suez.py?

**Comment by pira** [comment]
suez.py does not always run updatechanpolicy. in fact it never does unless you do use automated fee setting feature of it.

**Comment by prusnak** [comment]
Yes, don't break when you modify channel settings.
