### ISSUE TITLE
Display in Min & Max HTLCs

### ISSUE THREAD

**Issue by feelancer21** [prusnak/suez#30]
Hey, it would be great if there is the option to include Min and Max HTLCs of both sides of each channels. Because these are 4 additional figures it is better when they are only displayed if a command line parameter is set.

Regards Steff

**Comment by lirre8** [comment]
I wouldn't mind having this feature, it shouldn't be much work to fix.

@prusnak Do you find this reasonable? If so, how about adding an option `--show_minmax_htlc` which displays the 4 additional columns?

**Comment by prusnak** [comment]
> @prusnak Do you find this reasonable? If so, how about adding an option `--show_minmax_htlc` which displays the 4 additional columns?

I like it! Feel free to send a PR and I'll review it

**Comment by lirre8** [comment]
PR: https://github.com/prusnak/suez/pull/44

**Comment by lirre8** [comment]
The PR was merged so I think this issue can be closed?
