### ISSUE TITLE
Version for Terminal Web Scores

### ISSUE THREAD

**Issue by feelancer21** [prusnak/suez#38]
https://ln-scores.prod.lightningcluster.com/availability/v1/btc_summary.json is outdated.

You should switch to https://ln-scores.prod.lightningcluster.com/availability/v2/btc_summary.json

**Comment by prusnak** [comment]
Fixed in https://github.com/prusnak/suez/commit/7f2fdf45e52dc98410f9741e14636046c2d7df6b
