### ISSUE TITLE
Inaccurate local fees calculation

### ISSUE THREAD

**Issue by lirre8** [prusnak/suez#40]
Local fees for each channel are added as an integer value of number of sats, which means that any decimals are lost resulting in the fees displayed in the table might be very inaccurate from the truth.

A solution would be to store the fees as milli sats on the channel object. Both lnd and cln returns the fee as msat. And then divide by 1000 and round to nearest integer when setting the values to be displayed in the table.

I have working code for this running locally. Let me know if you want me to create a PR.

**Comment by prusnak** [comment]
Yes, please, create a PR. Thanks! 🙏

**Comment by lirre8** [comment]
Done: https://github.com/prusnak/suez/pull/41
