### ISSUE TITLE
Add arguments to show only public or only private channels

### ISSUE THREAD

**Issue by lirre8** [prusnak/suez#42]
Not sure if this feature makes sense? But I find it very useful to look at public and private channels separately. Could be implemented by adding '--only-public' and '--only-private' arguments and only show channels accordingly.

**Comment by prusnak** [comment]
Maybe we can add the following option:

`--channels={both,public,private,split}`

Where `both` is current behaviour, `public` shows only public, `private` shows only private and `split` shows public first and then private?

Would you like to create a PR with this option?

**Comment by lirre8** [comment]
Yes, that would be good. I'll create a PR

**Comment by lirre8** [comment]
What do you think about naming it `all` instead of `both`? Feels more natural I think to use `--channels=all` instead of `--channels=both`

**Comment by prusnak** [comment]
Sure, `all` sounds good

**Comment by lirre8** [comment]
Created this PR: https://github.com/prusnak/suez/pull/43

Btw, while testing with cln I noticed that there are fields used in the code that are no longer available in the latest version of lightning-cli, `msatoshi_total` and `msatoshi_to_us`, and one field that is treated as string in the code but is returned as int, `last_tx_fee_msat`.

**Comment by prusnak** [comment]
#43 merged

Thanks!
